### ISSUE TITLE
How to get the github icon in the top corner and search to show up on base website

### ISSUE THREAD

**Issue by pauleaster** [kogeletey/karzok#3]
I can't get the icons that you have in the top right corner to show up. They look like they are related to `config.extra.logotype` in `macros.html` but I am not sure what I need to put in `config.toml` file to get these working. If I clone this repo and build/serve with Zola, then I can see these icons. But when I use it as a template then they don't show up. Any suggestions?

Cheers!

 
![Search and icons](https://user-images.githubusercontent.com/42950830/144416787-99c0ad70-dae3-4458-8df8-61d26e5a67ba.png)

**Comment by kogeletey** [comment]
The parameter `config.extra.logotype` is responsible for the logo on the left, and on the right, you should use the parameter `[[extra.header_right]]` in which icons in svg format and a link are embedded.
Example: 
```toml
[[extra.header_right]]
link = "https://github.com/kogeletey/karzok"
svg = '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 24 24"><path d="M12 2A10 10 0 0 0 2 12c0 4.42 2.87 8.17 6.84 9.5c.5.08.66-.23.66-.5v-1.69c-2.77.6-3.36-1.34-3.36-1.34c-.46-1.16-1.11-1.47-1.11-1.47c-.91-.62.07-.6.07-.6c1 .07 1.53 1.03 1.53 1.03c.87 1.52 2.34 1.07 2.91.83c.09-.65.35-1.09.63-1.34c-2.22-.25-4.55-1.11-4.55-4.92c0-1.11.38-2 1.03-2.71c-.1-.25-.45-1.29.1-2.64c0 0 .84-.27 2.75 1.02c.79-.22 1.65-.33 2.5-.33c.85 0 1.71.11 2.5.33c1.91-1.29 2.75-1.02 2.75-1.02c.55 1.35.2 2.39.1 2.64c.65.71 1.03 1.6 1.03 2.71c0 3.82-2.34 4.66-4.57 4.91c.36.31.69.92.69 1.85V21c0 .27.16.59.67.5C19.14 20.16 22 16.42 22 12A10 10 0 0 0 12 2z" fill="currentColor"></path></svg>'
```
